name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: articles/er-metrics-library/01_article.tex
          working_directory: articles/er-metrics-library
      - name: Upload PDF
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: main.pdf